---

- name: If host running arch or derivative
  include: arch.yml
  when: 
    ansible_pkg_mgr == 'pacman'

- name: If host running ubuntu
  include: ubuntu_14_04.yml
  when: 
    ansible_distribution == 'Ubuntu' 
    and 
    (
      ansible_distribution_version == '14.04'
      or
      ansible_distribution_version == '12.04'
    )

